### ISSUE TITLE
Row size can not be configured (at least for 18 modules)

### ISSUE THREAD

**Issue by Arnaud73** [militu/electrical-panel-label#1]
Hi,

Thanks a lot for this nice tool, it seems quite polished but require a few improvements before anyone can use on his/her own. I discovered it by chance and gave it a try on my own installation. I'm going to log a few issues for each problem I encountered.

First issue, it does not ask for a row length. I seem to accommodate up to 15 units in a row, however, some installations reach 18 modules per row. Some are smaller for secondary electric enclosures (I have also one 8 module model)

**Comment by militu** [comment]
Hi @Arnaud73,

Thank you for your feedback on the tool. Let me clarify how it works, especially for your 18-module setup (I had the same use case).

The tool actually adapts to any number of modules while maintaining accurate sizes:

- Default: A4 landscape (fits 15 modules per row)
- Creates additional rows for larger setups
- Module sizes remain fixed for accuracy

For your 18-module electrical board on A4 paper:

- The tool will necessarily create two rows: 15 modules and 3 modules
- This split is required due to fixed module sizes and A4 width limitations
- Print both rows
- Cut and align them side-by-side for your full 18-module layout

While A4 paper requires this two-row approach, you can change to larger paper sizes (like A3) in the global settings if your printer supports it. This would allow all 18 modules on one row.
Let me know if you need any further explanation for your setup of if you have any suggestions.
